apiVersion: v1
kind: Secret
metadata:
  name: microservice-postgresql
  namespace: jhipster
  labels:
    app: microservice-postgresql
type: Opaque
data:
  postgresql-password: NWFlNTIyYzM1MjM4YTc3Mzc4MGQ1MGYyNTViN2VmNTg4NjI3OGY2ODEzNDBlYTJhNGIxYmYxOWRiOTlk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-postgresql
  namespace: jhipster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-postgresql
  template:
    metadata:
      labels:
        app: microservice-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:12.1
          env:
            - name: POSTGRES_USER
              value: microservice
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservice-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-postgresql
  namespace: jhipster
spec:
  selector:
    app: microservice-postgresql
  ports:
    - port: 5432
