commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: jhipster

resources:
  - namespace.yml
  # Individual apps
  - microservice/microservice-deployment.yml
  - microservice/microservice-service.yml
  - microservice/microservice-postgresql.yml
  # service discovery eureka/consul
  - registry/jhipster-registry.yml
  - registry/application-configmap.yml

patchesJson6902:
